discourse/rubocop-discourse

lib/rubocop/cop/discourse_cops.rb

Use `time_eq` matcher with timestamps in specs.
```rb
expect(user.created_at).to eq(Time.zone.now)
expect(user.created_at).to eq_time(Time.zone.now)
```

FEATURE: Add a `time_eq` matcher cop

---

lib/rubocop/cop/discourse_cops.rb

Use `Time.zone.now` instead of `Time.new` without arguments.
```rb
now = Time.new
now = Time.zone.now
```

FEATURE: Add a Time.new cop

---

lib/rubocop/cop/discourse/no_direct_multisite_manipulation.rb

Use `type: :multisite` example setting instead of modifying `Rails.configuration.multisite`.
```rb
it "works" do
Rails.configuration.multisite = true
do_something
end
it "works", type: :multisite do
do_something
end
```

FEATURE: Add `NoDirectMultisiteManipulation` cop

---

config/default.yml
lib/rubocop/cop/discourse/no_json_parse_response.rb

"Use `response.parsed_body` instead of `JSON.parse(response.body)` in specs."

No JSON.parse(response.body) in specs

---

config/default.yml
lib/rubocop/cop/discourse/no_nokogiri_html_fragment.rb

Nokogumbo changes are merged to Discourse https://github.com/discourse/discourse/pull/9577
We should protect codebase to not use Nokogiri::HTML anymore

FEATURE: Add `NoNokogiriHtmlFragment` cop

---

rubocop-discourse.gemspec
rubocop-rspec.yml

Updates rubocop-rspec to 2.0.0 an bumps rubocop-discourse to 2.4.1

DEV: Remove a retired InvalidPredicateMatcher option

---

rubocop-core.yml
rubocop-discourse.gemspec

This is recommended by syntax_tree for compatibility with some `Style/` cops. We don't seem to have any problematic cops enabled, so this is unnecessary and introduces unnecessary work to manually fix long lines. We use syntax_tree to reduce line length **when it can be done automatically**.

Remove Layout/LineLength from syntax_tree_compat

---

default.yml
rubocop-core.yml
rubocop-discourse.gemspec

1ed27272 intended to remove the LineLength restriction, but the default is enabled to we need to explicitly disable it

Disable Layout/LineLength for syntax_tree_compat

---

.github/workflows/ci.yml
config/default.yml
rubocop-core.yml
rubocop-discourse.gemspec
rubocop-rspec.yml
stree-compat.yml

Fixes parsing issues with rubocop 1.48.1
Also:
* Enable new security rule (`Security/CompoundHash`)
* Update `Style/HashSyntax` options (`EnforcedShorthandSyntax: either`) so it doesn't spam warnings all over the place after the ruby version syntax change
* And lint yaml (" vs ')

DEV: Update target ruby version

---

rubocop-discourse.gemspec
rubocop-rspec.yml
spec/lib/rubocop/cop/no_add_reference_active_record_migrations_spec.rb
spec/lib/rubocop/cop/no_mixing_multisite_and_standard_specs_spec.rb
spec/lib/rubocop/cop/no_mocking_jobs_enqueue_spec.rb
spec/lib/rubocop/cop/no_reset_column_information_migrations_spec.rb
spec/lib/rubocop/cop/only_top_level_multisite_specs_spec.rb
spec/lib/rubocop/cop/time_eq_matcher_spec.rb

This PR enables these cops:
- `RSpec/LeadingSubject`
- `RSpec/EmptyLineAfterSubject`
- `RSpec/NamedSubject`

DEV: Enable some cops related to RSpec subject

---

rubocop-rspec.yml

Those were moved in rubocop-rspec 2.22.0 (see: https://github.com/rubocop/rubocop-rspec/pull/1583)

DEV: Update FactoryBot rule names

---

rubocop-rspec.yml

```
Error: The `RSpec/FilePath` cop has been split into `RSpec/SpecFilePathFormat` and `RSpec/SpecFilePathSuffix`.
(obsolete configuration found in vendor/bundle/ruby/3.0.0/gems/rubocop-discourse-3.3.0/rubocop-rspec.yml, please update it)
```
Removed in [rubocop-rspec 2.24.0](https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2240-2023-09-08)

DEV: Remove obsolete cop

---

rubocop-core.yml
rubocop-discourse.gemspec

You can't just replace `:true`/`:false` with `true`/`false` and expect it to work the same 😅

FIX: Disable autofix for BooleanSymbol

---

rubocop-capybara.yml
rubocop-discourse.gemspec
rubocop-factory_bot.yml
rubocop-rspec.yml
stree-compat.yml

RuboCop RSpec used to contain departments for Capybara and FactoryBot cops, but those are being split out into `rubocop-capybara` and `rubocop-factory_bot` gems respectively. This change updates our gemspec and configuration files to reflect that.
It also silences the extension suggestion that otherwise shows up after each run, e.g.:
```
Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
* rubocop-rake (https://rubygems.org/gems/rubocop-rake)
```

DEV: Honor split RuboCop gems

---

lib/rubocop/cop/discourse/fabricator_shorthand.rb
spec/lib/rubocop/cop/fabricator_shorthand_spec.rb
stree-compat.yml

In https://github.com/discourse/discourse/pull/24314, @danielwaterworth introduced the ability to use `#fab!` with a shorthand when simply fabricating a vanilla record with the same name as the assigned `let`, e.g.:
```ruby
fab!(:user) { Fabricate(:user) }
```
can become:
```ruby
fab!(:user)
```
This PR introduces a cop that highlights places where this shorthand can be used.

FEATURE: Add a cop that checks for potential fabricator shorthand use

---

.rubocop.yml
config/default.yml
lib/rubocop-discourse.rb
lib/rubocop/cop/discourse/plugins/call_requires_plugin.rb
lib/rubocop/cop/discourse/plugins/namespace_constants.rb
lib/rubocop/cop/discourse/plugins/namespace_methods.rb
lib/rubocop/cop/discourse/plugins/no_monkey_patching.rb
lib/rubocop/cop/discourse/plugins/use_plugin_instance_on.rb
lib/rubocop/cop/discourse/plugins/use_require_relative.rb
lib/rubocop/cop/discourse_cops.rb
rubocop-discourse.gemspec
spec/fixtures/controllers/bad_controller.rb
spec/fixtures/controllers/base_controller.rb
spec/fixtures/controllers/good_controller.rb
spec/fixtures/controllers/inherit_from_outside_controller.rb
spec/fixtures/controllers/namespaced_parent_controller.rb
spec/fixtures/controllers/no_requires_plugin_controller.rb
spec/fixtures/controllers/requires_plugin_controller.rb
spec/lib/rubocop/cop/plugins/call_requires_plugin_spec.rb
spec/lib/rubocop/cop/plugins/namespace_constants_spec.rb
spec/lib/rubocop/cop/plugins/namespace_methods_spec.rb
spec/lib/rubocop/cop/plugins/no_monkey_patching_spec.rb
spec/lib/rubocop/cop/plugins/use_plugin_instance_on_spec.rb
spec/lib/rubocop/cop/plugins/use_require_relative_spec.rb

This patch adds some new rules to have saner defaults for our plugins. These rules should help in particular with disabled plugins.
The new cops are:
* Discourse/Plugins/CallRequiresPlugin: checks `requires_plugin` is called in controllers.
* Discourse/Plugins/DiscourseEvent: checks `on` is called instead of `DiscourseEvent.on`.
* Discourse/Plugins/NamespaceConstants: checks constants are not defined outside the plugin namespace.
* Discourse/Plugins/NamespaceMethods: checks methods are not defined outside the plugin namespace.
* Discourse/Plugins/NoMonkeyPatching: checks existing classes are not patched in `plugin.rb` using `class_eval`.
* Discourse/Plugins/UseRequireRelative: checks `load` is not used to load dependencies.

FEATURE: Add cops for plugins

---

.github/workflows/ci.yml
lib/rubocop/cop/discourse/no_add_reference_active_record_migrations.rb
lib/rubocop/cop/discourse/no_chdir.rb
lib/rubocop/cop/discourse/no_direct_multisite_manipulation.rb
lib/rubocop/cop/discourse/no_json_parse_response.rb
lib/rubocop/cop/discourse/no_mixing_multisite_and_standard_specs.rb
lib/rubocop/cop/discourse/no_mocking_jobs.rb
lib/rubocop/cop/discourse/no_nokogiri_html_fragment.rb
lib/rubocop/cop/discourse/no_reset_column_information_in_migrations.rb
lib/rubocop/cop/discourse/no_time_new_without_args.rb
lib/rubocop/cop/discourse/no_uri_escape_encode.rb
lib/rubocop/cop/discourse/only_top_level_multisite_specs.rb
lib/rubocop/cop/discourse/time_eq_matcher.rb
rubocop-discourse.gemspec
spec/lib/rubocop/cop/no_add_reference_active_record_migrations_spec.rb
spec/lib/rubocop/cop/no_mixing_multisite_and_standard_specs_spec.rb
spec/lib/rubocop/cop/no_mocking_jobs_enqueue_spec.rb
spec/lib/rubocop/cop/no_reset_column_information_migrations_spec.rb
spec/lib/rubocop/cop/only_top_level_multisite_specs_spec.rb
spec/lib/rubocop/cop/time_eq_matcher_spec.rb

> warning: Inheriting from `RuboCop::Cop::Cop` is deprecated. Use `RuboCop::Cop::Base` instead.

DEV: Stop inheriting from deprecated Rubocop::Cop::Cop

---

rubocop-discourse.gemspec
rubocop-rails.yml

We have some migrations that are executing code outside of reversible methods. This cop guards against that. 
I'll merge once all our core/plugins/themes have this resolved in separate PRs.

DEV: add Rails/ReversibleMigrationMethodDefinition cop

---

rubocop-core.yml
rubocop-discourse.gemspec

> [Constants should always be assigned in the same location. And its value should always be the same. If constants are assigned in multiple locations, the result may vary depending on the order of require.](https://docs.rubocop.org/rubocop/cops_lint.html#lintorassignmenttoconstant)

Enable Lint/OrAssignmentToConstant

---

rubocop-core.yml
rubocop-discourse.gemspec

There is no reason we should allow a constant to be mutable.
See https://docs.rubocop.org/rubocop/cops_style.html#stylemutableconstant
This could have prevented a bug like https://github.com/discourse/discourse/commit/4840060568e8066ed19ed35eb81fb4bfb97fea88

Enables Style/MutableConstant cop

---

config/default.yml
lib/rubocop-discourse.rb
lib/rubocop/cop/discourse/services/empty_lines_around_blocks.rb
lib/rubocop/cop/discourse/services/group_keywords.rb
rubocop-discourse.gemspec
spec/lib/rubocop/cop/discourse/services/empty_lines_around_blocks_spec.rb
spec/lib/rubocop/cop/discourse/services/group_keywords_spec.rb

This PR introduces two new cops aimed at services:
- `Discourse/Services/EmptyLinesAroundBlocks`: checks for missing empty
lines around multiline blocks. It has autocorrect support.
- `Discourse/Services/GroupKeywords`: checks for extra empty lines for
service keywords (not block ones). It has autocorrect support.
---
Results can be seen here: https://github.com/discourse/discourse/pull/29997

FEATURE: Add cops for services

---

lib/rubocop/discourse/version.rb
rubocop-rails.yml

…as it's unsafe, because the autofix breaks mini_sql code (that only looks like AR code)

DEV: Disable `Rails/WhereNot` rule

---

lib/rubocop/discourse/version.rb
rubocop-rails.yml

…because it's unsafe due to a Rails bug

DEV: Disable `Rails/WhereMissing` rule
